### PR TITLE
This is what you should ask when hiring

### PR DESCRIPTION
**Pull request by gabbyslome**
Any other advice for when hiring?  @nickmoreno @bennytawook @mattybachs @leichler08 @ereilly15 @kpluswax

### CODE REVIEW

**Comment by kpluswax** [comment]
@gabbyslome I think you need to get a link and a photo in there.  Use this syntax:

[LINK TEXT](www.thisistheurl.com)
alt text

**Comment by gabbyslome** [comment]
@kpluswax oh yeah thanks!!! hang on :japanese_goblin:

**Comment by kpluswax** [comment]
Dang @gabbyslome those updates look tight.  Great point about Hacker News too.

alt text

**Comment by nickmoreno** [comment]
This looks great to me. Great work @gabbyslome. @kpluswax Let's tone down the pornography. This is a family fork.

**Comment by ereilly15** [comment]
@gabbyslome looks good.  Some characteristics to consider when hiring include a developer that keeps asking questions, is constantly trying to learn, knows multiple solutions to a problem, is able to see the big picture, and is inquisitive.

**Comment by kpluswax** [comment]
BTW this looks good to me.  Fire the laser :+1:

**Pull request merged**
