### PR TITLE
How to bid a project

### PR DESCRIPTION
**Pull request by nickmoreno**
Need some feedback @kpluswax @mattybachs @bennytawook @gabbyslome @leichler08 @ereilly15

### CODE REVIEW

**Comment by mattybachs** [comment]
@nickmoreno This is great.  Doesn't it feel counterintuitive to do fixed bids when we literally ave no clue what the engineers are doing all day?  Don't get me wrong, I understand why, but it's still funny that it's weird this is the convention.  

Also thanks for calling us all dumb in your opening sentence.  

FYI if you want to look legit to these guys, [just open this baby up](www.hackertyper.net) and everyone will take you seriously:

**Comment by mattybachs** [comment]
Oh yeah and this is great :+1:

**Comment by kpluswax** [comment]
Yo @mattybachs you seem to think "this is great"- you said it twice.  

Now that I've made fun of @mattybachs, I hereby approve this branch. FIRE THE LASER :+1: 

PS @nickmoreno, I happen to also think this is great, but dont let that get to your head

alt text

**Comment by mattybachs** [comment]
@kpluswax thanks for your support, man.

alt text

**Pull request merged**
