### PR TITLE
Outline of the differences between NoSQL database types

### PR DESCRIPTION
**Pull request by kpluswax**
This is a summary of the main use cases for the four main NoSQL database types.  

@mattybachs and @bennytawook After careful review, I don't think you guys should use MongoDB for Wandering Bear :coffee: .  

I'll still buy it though, am I right @gabbyslome, @nickmoreno @leichler08 and @ereilly15 ??  I think you should just use SQL/Relational and keep it :100: :co :laughing:

### CODE REVIEW

**Comment by ereilly15** [comment]
@kpluswax - makes sense.  I would stick with using a NoSQL option - it will allow for more agile development and be easier to use when trying to deal with a large amount of data.

**Comment by kpluswax** [comment]
@ereilly15 I wonder if at this scale they even need their own database provider?  @bennytawook how do you manage your databases now?  Shopify?  Excel?  Maybe we start thinking about databases once you're taking down a few thousand boxes a week? :racehorse:

**Comment by kpluswax** [comment]
Ok team, can you give me the :+1: if you're ready to accept this pull?  THANKSSSSSS

**Comment by gabbyslome** [comment]
Looks good to me.  :+1:

**Comment by nickmoreno** [comment]
Did any of you actually read this before giving a :thumbsup:?

I award you no points

**Comment by mattybachs** [comment]
Yeah I agree with @nickmoreno - 

@kpluswax you should prob format this so human being can actually read it.

**Pull request merged**
